
public class Tela_Ani {

    static void aguardar(int segundos) {
        try {
            Thread.sleep(segundos * 500);
        } catch (InterruptedException ex) {
            throw new RuntimeException("Erro ao tentar esperar");
        }
    }

    static void l1() {
        Fjalp2.getTerminal().setCorFonte(CorFonte.CYAN);
        Fjalp2.getTerminal().setPosicaoCursor(40, 6);
        Fjalp2.getTerminal().escreva(" ______                                             __                 ");
        Fjalp2.getTerminal().setPosicaoCursor(41, 6);
        Fjalp2.getTerminal().escreva("|      |.---.-.----.----.-----.-----.---.-.-----.--|  |.-----.         ");
        Fjalp2.getTerminal().setPosicaoCursor(42, 6);
        Fjalp2.getTerminal().escreva("|   ---||  _  |   _|   _|  -__|  _  |  _  |     |  _  ||  _  |__");
        Fjalp2.getTerminal().setPosicaoCursor(43, 6);
        Fjalp2.getTerminal().escreva("|______||___._|__| |__| |_____|___  |___._|__|__|_____||_____|__|");
        Fjalp2.getTerminal().setPosicaoCursor(44, 6);
        Fjalp2.getTerminal().escreva("                              |_____|                                ");
        Fjalp2.getTerminal().resetCor();
    }

    static void l2() {
        Fjalp2.getTerminal().setCorFonte(CorFonte.CYAN);
        Fjalp2.getTerminal().setPosicaoCursor(40, 6);
        Fjalp2.getTerminal().escreva(" ______                                             __              ");
        Fjalp2.getTerminal().setPosicaoCursor(41, 6);
        Fjalp2.getTerminal().escreva("|      |.---.-.----.----.-----.-----.---.-.-----.--|  |.-----.      ");
        Fjalp2.getTerminal().setPosicaoCursor(42, 6);
        Fjalp2.getTerminal().escreva("|   ---||  _  |   _|   _|  -__|  _  |  _  |     |  _  ||  _  |   __ ");
        Fjalp2.getTerminal().setPosicaoCursor(43, 6);
        Fjalp2.getTerminal().escreva("|______||___._|__| |__| |_____|___  |___._|__|__|_____||_____|  |__|");
        Fjalp2.getTerminal().setPosicaoCursor(44, 6);
        Fjalp2.getTerminal().escreva("                              |_____|                                ");
        Fjalp2.getTerminal().resetCor();
    }

    static void l3() {
        Fjalp2.getTerminal().setCorFonte(CorFonte.CYAN);
        Fjalp2.getTerminal().setPosicaoCursor(40, 6);
        Fjalp2.getTerminal().escreva(" ______                                             __                 ");
        Fjalp2.getTerminal().setPosicaoCursor(41, 6);
        Fjalp2.getTerminal().escreva("|      |.---.-.----.----.-----.-----.---.-.-----.--|  |.-----.         ");
        Fjalp2.getTerminal().setPosicaoCursor(42, 6);
        Fjalp2.getTerminal().escreva("|   ---||  _  |   _|   _|  -__|  _  |  _  |     |  _  ||  _  |      __ ");
        Fjalp2.getTerminal().setPosicaoCursor(43, 6);
        Fjalp2.getTerminal().escreva("|______||___._|__| |__| |_____|___  |___._|__|__|_____||_____|     |__|");
        Fjalp2.getTerminal().setPosicaoCursor(44, 6);
        Fjalp2.getTerminal().escreva("                              |_____|                                ");
        Fjalp2.getTerminal().resetCor();
    }

    static void f1() {
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().setPosicaoCursor(40, 6);
        Fjalp2.getTerminal().escreva(" _______ __               __ __                       __        ");
        Fjalp2.getTerminal().setPosicaoCursor(41, 6);
        Fjalp2.getTerminal().escreva("|    ___|__|.-----.---.-.|  |__|.-----.---.-.-----.--|  |.-----.");
        Fjalp2.getTerminal().setPosicaoCursor(42, 6);
        Fjalp2.getTerminal().escreva("|    ___|  ||     |  _  ||  |  ||-- __|  _  |     |  _  ||  _  |__");
        Fjalp2.getTerminal().setPosicaoCursor(43, 6);
        Fjalp2.getTerminal().escreva("|___|   |__||__|__|___._||__|__||_____|___._|__|__|_____||_____|__|");
        Fjalp2.getTerminal().resetCor();

    }

    static void f2() {
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().setPosicaoCursor(40, 6);
        Fjalp2.getTerminal().escreva(" _______ __               __ __                       __        ");
        Fjalp2.getTerminal().setPosicaoCursor(41, 6);
        Fjalp2.getTerminal().escreva("|    ___|__|.-----.---.-.|  |__|.-----.---.-.-----.--|  |.-----.");
        Fjalp2.getTerminal().setPosicaoCursor(42, 6);
        Fjalp2.getTerminal().escreva("|    ___|  ||     |  _  ||  |  ||-- __|  _  |     |  _  ||  _  |   __");
        Fjalp2.getTerminal().setPosicaoCursor(43, 6);
        Fjalp2.getTerminal().escreva("|___|   |__||__|__|___._||__|__||_____|___._|__|__|_____||_____|  |__|");
        Fjalp2.getTerminal().resetCor();

    }

    static void f3() {
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().setPosicaoCursor(40, 6);
        Fjalp2.getTerminal().escreva(" _______ __               __ __                       __        ");
        Fjalp2.getTerminal().setPosicaoCursor(41, 6);
        Fjalp2.getTerminal().escreva("|    ___|__|.-----.---.-.|  |__|.-----.---.-.-----.--|  |.-----.");
        Fjalp2.getTerminal().setPosicaoCursor(42, 6);
        Fjalp2.getTerminal().escreva("|    ___|  ||     |  _  ||  |  ||-- __|  _  |     |  _  ||  _  |      __ ");
        Fjalp2.getTerminal().setPosicaoCursor(43, 6);
        Fjalp2.getTerminal().escreva("|___|   |__||__|__|___._||__|__||_____|___._|__|__|_____||_____|     |__|");
        Fjalp2.getTerminal().resetCor();
    }

    static void g2() {
        int x = 18;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().setPosicaoCursor(13, x);
        Fjalp2.getTerminal().escreva("              _v->#H#P? '':o<>\\_");
        Fjalp2.getTerminal().setPosicaoCursor(14, x);
        Fjalp2.getTerminal().escreva("          .,dP` `''  ''-o.+H6&MMMHo_");
        Fjalp2.getTerminal().setPosicaoCursor(15, x);
        Fjalp2.getTerminal().escreva("        oHMH9'         `?&bHMHMMMMMMHo.");
        Fjalp2.getTerminal().setPosicaoCursor(16, x);
        Fjalp2.getTerminal().escreva("      oMP'' '           ooMP*#&HMMMMMMM?.");
        Fjalp2.getTerminal().setPosicaoCursor(17, x);
        Fjalp2.getTerminal().escreva("    ,M*          -     `*MSdob//`^&##MMMH\\");
        Fjalp2.getTerminal().setPosicaoCursor(18, x);
        Fjalp2.getTerminal().escreva("   d*'                .,MMMMMMH#o>#ooMMMMMb");
        Fjalp2.getTerminal().setPosicaoCursor(19, x);
        Fjalp2.getTerminal().escreva("  HM-                :HMMMMMMMMMMMMMMM&HM[R\\");
        Fjalp2.getTerminal().setPosicaoCursor(20, x);
        Fjalp2.getTerminal().escreva(" d'Z\\.              9MMMMMMMMMMMMMMMMM[HMM|:");
        Fjalp2.getTerminal().setPosicaoCursor(21, x);
        Fjalp2.getTerminal().escreva("-H    -              MMMMMMMMMMMMMMMMMMMbMP' :");
        Fjalp2.getTerminal().setPosicaoCursor(22, x);
        Fjalp2.getTerminal().escreva(":??Mb#               `9MMMMMMMMMMMMMMMMMMH#! .");
        Fjalp2.getTerminal().setPosicaoCursor(23, x);
        Fjalp2.getTerminal().escreva(": MMMMH#,              '*''''`#HMMMMMMMMMMH  -");
        Fjalp2.getTerminal().setPosicaoCursor(24, x);
        Fjalp2.getTerminal().escreva("||MMMMMM6\\.                   {MMMMMMMMMH'  :");
        Fjalp2.getTerminal().setPosicaoCursor(25, x);
        Fjalp2.getTerminal().escreva(":|MMMMMMMMMMHo                 `9MMMMMMMM'   .");
        Fjalp2.getTerminal().setPosicaoCursor(26, x);
        Fjalp2.getTerminal().escreva(". HMMMMMMMMMMP'                 !MMMMMMMM    `");
        Fjalp2.getTerminal().setPosicaoCursor(27, x);
        Fjalp2.getTerminal().escreva("- `#MMMMMMMMM                   HMMMMMMM*,/  :");
        Fjalp2.getTerminal().setPosicaoCursor(28, x);
        Fjalp2.getTerminal().escreva(" :  ?MMMMMMMF                   HMMMMMM',P' :");
        Fjalp2.getTerminal().setCorFonte(CorFonte.CYAN);
        Fjalp2.getTerminal().setPosicaoCursor(29, x);
        Fjalp2.getTerminal().escreva("  .  HMMMMR'                    {MMMMP' ^' -");
        Fjalp2.getTerminal().setPosicaoCursor(30, x);
        Fjalp2.getTerminal().escreva("   : `HMMMT                     iMMH'     .'");
        Fjalp2.getTerminal().setPosicaoCursor(31, x);
        Fjalp2.getTerminal().escreva("    -.`HMH                               .");
        Fjalp2.getTerminal().setPosicaoCursor(32, x);
        Fjalp2.getTerminal().escreva("      -:*H                            . '");
        Fjalp2.getTerminal().setPosicaoCursor(33, x);
        Fjalp2.getTerminal().escreva("        -`\\,,   .                  .-");
        Fjalp2.getTerminal().setPosicaoCursor(34, x);
        Fjalp2.getTerminal().escreva("          ' .  _                 .-`");
        Fjalp2.getTerminal().setPosicaoCursor(35, x);
        Fjalp2.getTerminal().escreva("              '~\\.__,obb#q==~'''");

    }

    static void g2f() {
        int x = 18;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().setPosicaoCursor(13, x);
        Fjalp2.getTerminal().escreva("              _v->#H#P? '':o<>\\_");
        Fjalp2.getTerminal().setPosicaoCursor(14, x);
        Fjalp2.getTerminal().escreva("          .,dP` `''  ''-o.+H6&MMMHo_");
        Fjalp2.getTerminal().setPosicaoCursor(15, x);
        Fjalp2.getTerminal().escreva("        oHMH9'         `?&bHMHMMMMMMHo.");
        Fjalp2.getTerminal().setPosicaoCursor(16, x);
        Fjalp2.getTerminal().escreva("      oMP'' '           ooMP*#&HMMMMMMM?.");
        Fjalp2.getTerminal().setPosicaoCursor(17, x);
        Fjalp2.getTerminal().escreva("    ,M*          -     `*MSdob//`^&##MMMH\\");
        Fjalp2.getTerminal().setPosicaoCursor(18, x);
        Fjalp2.getTerminal().escreva("   d*'                .,MMMMMMH#o>#ooMMMMMb");
        Fjalp2.getTerminal().setPosicaoCursor(19, x);
        Fjalp2.getTerminal().escreva("  HM-                :HMMMMMMMMMMMMMMM&HM[R\\");
        Fjalp2.getTerminal().setPosicaoCursor(20, x);
        Fjalp2.getTerminal().escreva(" d'Z\\.              9MMMMMMMMMMMMMMMMM[HMM|:");
        Fjalp2.getTerminal().setCorFonte(CorFonte.CYAN);
        Fjalp2.getTerminal().setPosicaoCursor(21, x);
        Fjalp2.getTerminal().escreva("-H    -              MMMMMMMMMMMMMMMMMMMbMP' :");
        Fjalp2.getTerminal().setPosicaoCursor(22, x);
        Fjalp2.getTerminal().escreva(":??Mb#               `9MMMMMMMMMMMMMMMMMMH#! .");
        Fjalp2.getTerminal().setPosicaoCursor(23, x);
        Fjalp2.getTerminal().escreva(": MMMMH#,              '*''''`#HMMMMMMMMMMH  -");
        Fjalp2.getTerminal().setPosicaoCursor(24, x);
        Fjalp2.getTerminal().escreva("||MMMMMM6\\.                   {MMMMMMMMMH'  :");
        Fjalp2.getTerminal().setPosicaoCursor(25, x);
        Fjalp2.getTerminal().escreva(":|MMMMMMMMMMHo                 `9MMMMMMMM'   .");
        Fjalp2.getTerminal().setPosicaoCursor(26, x);
        Fjalp2.getTerminal().escreva(". HMMMMMMMMMMP'                 !MMMMMMMM    `");
        Fjalp2.getTerminal().setPosicaoCursor(27, x);
        Fjalp2.getTerminal().escreva("- `#MMMMMMMMM                   HMMMMMMM*,/  :");
        Fjalp2.getTerminal().setPosicaoCursor(28, x);
        Fjalp2.getTerminal().escreva(" :  ?MMMMMMMF                   HMMMMMM',P' :");
        Fjalp2.getTerminal().setPosicaoCursor(29, x);
        Fjalp2.getTerminal().escreva("  .  HMMMMR'                    {MMMMP' ^' -");
        Fjalp2.getTerminal().setPosicaoCursor(30, x);
        Fjalp2.getTerminal().escreva("   : `HMMMT                     iMMH'     .'");
        Fjalp2.getTerminal().setPosicaoCursor(31, x);
        Fjalp2.getTerminal().escreva("    -.`HMH                               .");
        Fjalp2.getTerminal().setPosicaoCursor(32, x);
        Fjalp2.getTerminal().escreva("      -:*H                            . '");
        Fjalp2.getTerminal().setPosicaoCursor(33, x);
        Fjalp2.getTerminal().escreva("        -`\\,,   .                  .-");
        Fjalp2.getTerminal().setPosicaoCursor(34, x);
        Fjalp2.getTerminal().escreva("          ' .  _                 .-`");
        Fjalp2.getTerminal().setPosicaoCursor(35, x);
        Fjalp2.getTerminal().escreva("              '~\\.__,obb#q==~'''");

    }

    static void g4() {
        int x = 18;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.CYAN);
        Fjalp2.getTerminal().setPosicaoCursor(13, x);
        Fjalp2.getTerminal().escreva("              _oo##'9MMHb':'-,o_");
        Fjalp2.getTerminal().setPosicaoCursor(14, x);
        Fjalp2.getTerminal().escreva("          .oH':HH$' '''  ''-\\7*R&o_");
        Fjalp2.getTerminal().setPosicaoCursor(15, x);
        Fjalp2.getTerminal().escreva("       .oHMMMHMH#9:         '\\bMMMMHo.");
        Fjalp2.getTerminal().setPosicaoCursor(16, x);
        Fjalp2.getTerminal().escreva("      dMMMMMM*'''`'           .oHM'H9MM?.");
        Fjalp2.getTerminal().setPosicaoCursor(17, x);
        Fjalp2.getTerminal().escreva("    ,MMMMMM'                   'HLbd<|?&H\\");
        Fjalp2.getTerminal().setPosicaoCursor(18, x);
        Fjalp2.getTerminal().escreva("   JMMH#H'                     |MMMMM#b>bHb");
        Fjalp2.getTerminal().setPosicaoCursor(19, x);
        Fjalp2.getTerminal().escreva("  :MH  .'\\                  `|MMMMMMMMMMMM&");
        Fjalp2.getTerminal().setPosicaoCursor(20, x);
        Fjalp2.getTerminal().escreva(" .:M:d-'|:b..                 9MMMMMMMMMMMMM+");
        Fjalp2.getTerminal().setPosicaoCursor(21, x);
        Fjalp2.getTerminal().escreva(":  '*H|      -                &MMMMMMMMMMMMMH:");
        Fjalp2.getTerminal().setPosicaoCursor(22, x);
        Fjalp2.getTerminal().escreva(".    `LvdHH#d?                `?MMMMMMMMMMMMMb");
        Fjalp2.getTerminal().setPosicaoCursor(23, x);
        Fjalp2.getTerminal().escreva(":      iMMMMMMH#b               `'*'''#HMMMMMM");
        Fjalp2.getTerminal().setPosicaoCursor(24, x);
        Fjalp2.getTerminal().escreva(".   . ,MMMMMMMMMMb\\.                  {MMMMMH");
        Fjalp2.getTerminal().setPosicaoCursor(25, x);
        Fjalp2.getTerminal().escreva("-     |MMMMMMMMMMMMMMHb,               `MMMMM|");
        Fjalp2.getTerminal().setPosicaoCursor(26, x);
        Fjalp2.getTerminal().escreva(":      |MMMMMMMMMMMMMMH'                &MMMM,");
        Fjalp2.getTerminal().setPosicaoCursor(27, x);
        Fjalp2.getTerminal().escreva("-       `#MMMMMMMMMMMM                 |MMMM6-");
        Fjalp2.getTerminal().setPosicaoCursor(28, x);
        Fjalp2.getTerminal().escreva(" :        `MMMMMMMMMM+                 ]MMMT/");
        Fjalp2.getTerminal().setPosicaoCursor(29, x);
        Fjalp2.getTerminal().escreva("  .       `MMMMMMMP'                   HMM*`");
        Fjalp2.getTerminal().setPosicaoCursor(30, x);
        Fjalp2.getTerminal().escreva("   -       |MMMMMH'                   ,M#'-");
        Fjalp2.getTerminal().setPosicaoCursor(31, x);
        Fjalp2.getTerminal().escreva("    '.     :MMMH|                       .-");
        Fjalp2.getTerminal().setPosicaoCursor(32, x);
        Fjalp2.getTerminal().escreva("      .     |MM                        -");
        Fjalp2.getTerminal().setPosicaoCursor(33, x);
        Fjalp2.getTerminal().escreva("       ` .   `#?..    .             ..'");
        Fjalp2.getTerminal().setPosicaoCursor(34, x);
        Fjalp2.getTerminal().escreva("           -.     _.             .-");
        Fjalp2.getTerminal().setPosicaoCursor(35, x);
        Fjalp2.getTerminal().escreva("              '-|.#qo__,,ob=~~-''");

    }

    static void g4f() {
        int x = 18;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().setPosicaoCursor(13, x);
        Fjalp2.getTerminal().escreva("              _oo##'9MMHb':'-,o_");
        Fjalp2.getTerminal().setPosicaoCursor(14, x);
        Fjalp2.getTerminal().escreva("          .oH':HH$' '''  ''-\\7*R&o_");
        Fjalp2.getTerminal().setPosicaoCursor(15, x);
        Fjalp2.getTerminal().escreva("       .oHMMMHMH#9:         '\\bMMMMHo.");
        Fjalp2.getTerminal().setPosicaoCursor(16, x);
        Fjalp2.getTerminal().escreva("      dMMMMMM*'''`'           .oHM'H9MM?.");
        Fjalp2.getTerminal().setPosicaoCursor(17, x);
        Fjalp2.getTerminal().escreva("    ,MMMMMM'                   'HLbd<|?&H\\");
        Fjalp2.getTerminal().setPosicaoCursor(18, x);
        Fjalp2.getTerminal().escreva("   JMMH#H'                     |MMMMM#b>bHb");
        Fjalp2.getTerminal().setPosicaoCursor(19, x);
        Fjalp2.getTerminal().escreva("  :MH  .'\\                  `|MMMMMMMMMMMM&");
        Fjalp2.getTerminal().setPosicaoCursor(20, x);
        Fjalp2.getTerminal().escreva(" .:M:d-'|:b..                 9MMMMMMMMMMMMM+");
        Fjalp2.getTerminal().setPosicaoCursor(21, x);
        Fjalp2.getTerminal().escreva(":  '*H|      -                &MMMMMMMMMMMMMH:");
        Fjalp2.getTerminal().setPosicaoCursor(22, x);
        Fjalp2.getTerminal().escreva(".    `LvdHH#d?                `?MMMMMMMMMMMMMb");
        Fjalp2.getTerminal().setPosicaoCursor(23, x);
        Fjalp2.getTerminal().escreva(":      iMMMMMMH#b               `'*'''#HMMMMMM");
        Fjalp2.getTerminal().setPosicaoCursor(24, x);
        Fjalp2.getTerminal().escreva(".   . ,MMMMMMMMMMb\\.                  {MMMMMH");
        Fjalp2.getTerminal().setPosicaoCursor(25, x);
        Fjalp2.getTerminal().escreva("-     |MMMMMMMMMMMMMMHb,               `MMMMM|");
        Fjalp2.getTerminal().setPosicaoCursor(26, x);
        Fjalp2.getTerminal().escreva(":      |MMMMMMMMMMMMMMH'                &MMMM,");
        Fjalp2.getTerminal().setPosicaoCursor(27, x);
        Fjalp2.getTerminal().escreva("-       `#MMMMMMMMMMMM                 |MMMM6-");
        Fjalp2.getTerminal().setPosicaoCursor(28, x);
        Fjalp2.getTerminal().escreva(" :        `MMMMMMMMMM+                 ]MMMT/");
        Fjalp2.getTerminal().setPosicaoCursor(29, x);
        Fjalp2.getTerminal().escreva("  .       `MMMMMMMP'                   HMM*`");
        Fjalp2.getTerminal().setPosicaoCursor(30, x);
        Fjalp2.getTerminal().escreva("   -       |MMMMMH'                   ,M#'-");
        Fjalp2.getTerminal().setPosicaoCursor(31, x);
        Fjalp2.getTerminal().escreva("    '.     :MMMH|                       .-");
        Fjalp2.getTerminal().setPosicaoCursor(32, x);
        Fjalp2.getTerminal().escreva("      .     |MM                        -");
        Fjalp2.getTerminal().setPosicaoCursor(33, x);
        Fjalp2.getTerminal().escreva("       ` .   `#?..    .             ..'");
        Fjalp2.getTerminal().setPosicaoCursor(34, x);
        Fjalp2.getTerminal().escreva("           -.     _.             .-");
        Fjalp2.getTerminal().setPosicaoCursor(35, x);
        Fjalp2.getTerminal().escreva("              '-|.#qo__,,ob=~~-''");

    }

    static void g6() {
        int x = 18;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.CYAN);
        Fjalp2.getTerminal().setPosicaoCursor(13, x);
        Fjalp2.getTerminal().escreva("              .oo>#&H6?*MMH:-.._");
        Fjalp2.getTerminal().setPosicaoCursor(14, x);
        Fjalp2.getTerminal().escreva("          .oHMMMR:'&MZ\\ ''  '  |$-_");
        Fjalp2.getTerminal().setPosicaoCursor(15, x);
        Fjalp2.getTerminal().escreva("       ..dMMMMMMMMdMMM#9\\       `'HHo.");
        Fjalp2.getTerminal().setPosicaoCursor(16, x);
        Fjalp2.getTerminal().escreva("     . ,dMMMMMMMMMMM'`' `           ?MP?.");
        Fjalp2.getTerminal().setPosicaoCursor(17, x);
        Fjalp2.getTerminal().escreva("    . |MMMMMMMMMMM'                 `'$b&\\");
        Fjalp2.getTerminal().setPosicaoCursor(18, x);
        Fjalp2.getTerminal().escreva("   -  |MMMMHH##M'                     HMMH?");
        Fjalp2.getTerminal().setPosicaoCursor(19, x);
        Fjalp2.getTerminal().escreva("  -   TTMM|    >..                  \\MMMMMH");
        Fjalp2.getTerminal().setPosicaoCursor(20, x);
        Fjalp2.getTerminal().escreva(" :     |MM\\,#-''$~b\\.              `MMMMMM+");
        Fjalp2.getTerminal().setPosicaoCursor(21, x);
        Fjalp2.getTerminal().escreva(".       ``'H&#        -               &MMMMMM|");
        Fjalp2.getTerminal().setPosicaoCursor(22, x);
        Fjalp2.getTerminal().escreva(":           *\\v,#MHddc.              `9MMMMMb");
        Fjalp2.getTerminal().setPosicaoCursor(23, x);
        Fjalp2.getTerminal().escreva(".               MMMMMMMM##\\            `'':HM");
        Fjalp2.getTerminal().setPosicaoCursor(24, x);
        Fjalp2.getTerminal().escreva("-          .  .HMMMMMMMMMMRo_.              |M");
        Fjalp2.getTerminal().setPosicaoCursor(25, x);
        Fjalp2.getTerminal().escreva(":             |MMMMMMMMMMMMMMMM#\\          :M");
        Fjalp2.getTerminal().setPosicaoCursor(26, x);
        Fjalp2.getTerminal().escreva("-              `HMMMMMMMMMMMMMMM'           |T");
        Fjalp2.getTerminal().setPosicaoCursor(27, x);
        Fjalp2.getTerminal().escreva(":               `*HMMMMMMMMMMMM'            H'");
        Fjalp2.getTerminal().setPosicaoCursor(28, x);
        Fjalp2.getTerminal().escreva(" :                 MMMMMMMMMMM|            |T");
        Fjalp2.getTerminal().setPosicaoCursor(29, x);
        Fjalp2.getTerminal().escreva("  .                MMMMMMMM?'             ./");
        Fjalp2.getTerminal().setPosicaoCursor(30, x);
        Fjalp2.getTerminal().escreva("  `.               MMMMMMH'              ./");
        Fjalp2.getTerminal().setPosicaoCursor(31, x);
        Fjalp2.getTerminal().escreva("    -.            |MMMH#'                .");
        Fjalp2.getTerminal().setPosicaoCursor(32, x);
        Fjalp2.getTerminal().escreva("      .           `MM*                . '");
        Fjalp2.getTerminal().setPosicaoCursor(33, x);
        Fjalp2.getTerminal().escreva("        -.         #M: .    .       .-");
        Fjalp2.getTerminal().setPosicaoCursor(34, x);
        Fjalp2.getTerminal().escreva("          ` .         .,         .-");
        Fjalp2.getTerminal().setPosicaoCursor(35, x);
        Fjalp2.getTerminal().escreva("              '-.-~ooHH__,,v~--`");

    }

    static void g6f() {
        int x = 18;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().setPosicaoCursor(13, x);
        Fjalp2.getTerminal().escreva("              .oo>#&H6?*MMH:-.._");
        Fjalp2.getTerminal().setPosicaoCursor(14, x);
        Fjalp2.getTerminal().escreva("          .oHMMMR:'&MZ\\ ''  '  |$-_");
        Fjalp2.getTerminal().setPosicaoCursor(15, x);
        Fjalp2.getTerminal().escreva("       ..dMMMMMMMMdMMM#9\\       `'HHo.");
        Fjalp2.getTerminal().setPosicaoCursor(16, x);
        Fjalp2.getTerminal().escreva("     . ,dMMMMMMMMMMM'`' `           ?MP?.");
        Fjalp2.getTerminal().setPosicaoCursor(17, x);
        Fjalp2.getTerminal().escreva("    . |MMMMMMMMMMM'                 `'$b&\\");
        Fjalp2.getTerminal().setPosicaoCursor(18, x);
        Fjalp2.getTerminal().escreva("   -  |MMMMHH##M'                     HMMH?");
        Fjalp2.getTerminal().setPosicaoCursor(19, x);
        Fjalp2.getTerminal().escreva("  -   TTMM|    >..                  \\MMMMMH");
        Fjalp2.getTerminal().setPosicaoCursor(20, x);
        Fjalp2.getTerminal().escreva(" :     |MM\\,#-''$~b\\.              `MMMMMM+");
        Fjalp2.getTerminal().setPosicaoCursor(21, x);
        Fjalp2.getTerminal().escreva(".       ``'H&#        -               &MMMMMM|");
        Fjalp2.getTerminal().setPosicaoCursor(22, x);
        Fjalp2.getTerminal().escreva(":           *\\v,#MHddc.              `9MMMMMb");
        Fjalp2.getTerminal().setPosicaoCursor(23, x);
        Fjalp2.getTerminal().escreva(".               MMMMMMMM##\\            `'':HM");
        Fjalp2.getTerminal().setPosicaoCursor(24, x);
        Fjalp2.getTerminal().escreva("-          .  .HMMMMMMMMMMRo_.              |M");
        Fjalp2.getTerminal().setPosicaoCursor(25, x);
        Fjalp2.getTerminal().escreva(":             |MMMMMMMMMMMMMMMM#\\          :M");
        Fjalp2.getTerminal().setPosicaoCursor(26, x);
        Fjalp2.getTerminal().escreva("-              `HMMMMMMMMMMMMMMM'           |T");
        Fjalp2.getTerminal().setPosicaoCursor(27, x);
        Fjalp2.getTerminal().escreva(":               `*HMMMMMMMMMMMM'            H'");
        Fjalp2.getTerminal().setPosicaoCursor(28, x);
        Fjalp2.getTerminal().escreva(" :                 MMMMMMMMMMM|            |T");
        Fjalp2.getTerminal().setPosicaoCursor(29, x);
        Fjalp2.getTerminal().escreva("  .                MMMMMMMM?'             ./");
        Fjalp2.getTerminal().setPosicaoCursor(30, x);
        Fjalp2.getTerminal().escreva("  `.               MMMMMMH'              ./");
        Fjalp2.getTerminal().setPosicaoCursor(31, x);
        Fjalp2.getTerminal().escreva("    -.            |MMMH#'                .");
        Fjalp2.getTerminal().setPosicaoCursor(32, x);
        Fjalp2.getTerminal().escreva("      .           `MM*                . '");
        Fjalp2.getTerminal().setPosicaoCursor(33, x);
        Fjalp2.getTerminal().escreva("        -.         #M: .    .       .-");
        Fjalp2.getTerminal().setPosicaoCursor(34, x);
        Fjalp2.getTerminal().escreva("          ` .         .,         .-");
        Fjalp2.getTerminal().setPosicaoCursor(35, x);
        Fjalp2.getTerminal().escreva("              '-.-~ooHH__,,v~--`");

    }

    static void g8() {
        int x = 18;
        int y = 13;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.CYAN);
        Fjalp2.getTerminal().setPosicaoCursor(y, x);
        Fjalp2.getTerminal().escreva("             _,\\?dZkMHF&$*q#b..");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          .//9MMMMMMM?:'HM\\\\'`-''`..");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("       ..`  :MMMMMMMMMMHMMMMH?_    `-\\");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("     .     .dMMMMMMMMMMMMMM''''       `\\.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    .      |MMMMMMMMMMMMMR              \\\\");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   -        T9MMMMMHH##M'                `?");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  :          (9MMM'    !':.               &k");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" .:            HMM\\_?p '':-b\\.          `ML");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("-                '''H&#,       :           |M|");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":                     ?\\,\\dMH#b#.         9b");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":                        |MMMMMMM##,        `*");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":                   .   +MMMMMMMMMMMo_       -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":                       HMMMMMMMMMMMMMM#,    :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":                        9MMMMMMMMMMMMMH'    .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(": .                       *HMMMMMMMMMMP     .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" :                          MMMMMMMMMH'     .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  -                        :MMMMMMM'`      .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  `.                       9MMMMM*'       -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    -.                    {MMM#'         :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("      -                  |MM'          .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("       `.                &M'..  .   ..'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          ' .             ._     .-");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("              '-. -voboo#&:,-.-`");
    }

    static void g8f() {
        int x = 18;
        int y = 13;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().setPosicaoCursor(y, x);
        Fjalp2.getTerminal().escreva("             _,\\?dZkMHF&$*q#b..");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          .//9MMMMMMM?:'HM\\\\'`-''`..");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("       ..`  :MMMMMMMMMMHMMMMH?_    `-\\");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("     .     .dMMMMMMMMMMMMMM''''       `\\.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    .      |MMMMMMMMMMMMMR              \\\\");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   -        T9MMMMMHH##M'                `?");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  :          (9MMM'    !':.               &k");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" .:            HMM\\_?p '':-b\\.          `ML");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("-                '''H&#,       :           |M|");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":                     ?\\,\\dMH#b#.         9b");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":                        |MMMMMMM##,        `*");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":                   .   +MMMMMMMMMMMo_       -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":                       HMMMMMMMMMMMMMM#,    :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":                        9MMMMMMMMMMMMMH'    .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(": .                       *HMMMMMMMMMMP     .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" :                          MMMMMMMMMH'     .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  -                        :MMMMMMM'`      .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  `.                       9MMMMM*'       -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    -.                    {MMM#'         :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("      -                  |MM'          .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("       `.                &M'..  .   ..'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          ' .             ._     .-");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("              '-. -voboo#&:,-.-`");
    }

    static void g10() {
        int x = 18;
        int y = 13;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.CYAN);
        Fjalp2.getTerminal().setPosicaoCursor(y, x);
        Fjalp2.getTerminal().escreva("             _\\oo\\?ddk9MRbS>v\\_");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          ..:>*''MMMMMMMMM:?|H?$?-.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("       ..- -     'HMMMMMMMMMMHMMMH\\_-.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("     .            dMMMMMMMMMMMMMMT'    .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    .             TMMMMMMMMMMMMMM       `.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   -               `&HMMMMMM#H#H:         .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  -               `\\7HMMH     |\\.        .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" :    `               HMM\\_?c`''+?\\..     :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("-                         '``#&#|      .     -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":                             `?,\\#MHdb.    .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":                                 |MMMMMH#.  :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":                            .   ,HMMMMMMMb, -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(": '                              4MMMMMMMMMMH`");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":   .                             9MMMMMMMMMT-");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":.`                               `#MMMMMMMH '");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" :      '                           HMMMMMH':");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  -                                |MMMMH' -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  `:                              |MMMH*' .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    '?                           dMM#'   .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("      \\.                      .dH'    .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("        -.                    ,M'-  ..'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          ` .                .. ..-`");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("              '-. .\\ooooboo<^.-`");
    }

    static void g10f() {
        int x = 18;
        int y = 13;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().setPosicaoCursor(y, x);
        Fjalp2.getTerminal().escreva("             _\\oo\\?ddk9MRbS>v\\_");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          ..:>*''MMMMMMMMM:?|H?$?-.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("       ..- -     'HMMMMMMMMMMHMMMH\\_-.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("     .            dMMMMMMMMMMMMMMT'    .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    .             TMMMMMMMMMMMMMM       `.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   -               `&HMMMMMM#H#H:         .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  -               `\\7HMMH     |\\.        .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" :    `               HMM\\_?c`''+?\\..     :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("-                         '``#&#|      .     -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":                             `?,\\#MHdb.    .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":                                 |MMMMMH#.  :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":                            .   ,HMMMMMMMb, -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(": '                              4MMMMMMMMMMH`");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":   .                             9MMMMMMMMMT-");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":.`                               `#MMMMMMMH '");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" :      '                           HMMMMMH':");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  -                                |MMMMH' -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  `:                              |MMMH*' .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    '?                           dMM#'   .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("      \\.                      .dH'    .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("        -.                    ,M'-  ..'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          ` .                .. ..-`");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("              '-. .\\ooooboo<^.-`");
    }

    static void g16() {
        int x = 18;
        int y = 13;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().setPosicaoCursor(y, x);
        Fjalp2.getTerminal().escreva("              _,o#bH\\??::?o?cbo_");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          .o#MH#**SH''' '`*H#'*#MHo_");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("        oHMMMH^  ^'    -  `      '*HHo.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("     .dMMM#'>>-                     `HM?.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    ,MH:R_o/                         `*MH\\");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   dMM' '                               'ML");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  HMR! '                                 `#k");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" d&'.                          -.          `L");
        Fjalp2.getTerminal().setCorFonte(CorFonte.CYAN);
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":M ::     `                                 `-");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("/| !|                                        -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("k.$-'                                        :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("}9R:!,,_.                                    .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("\\::\\':`*M#\\-'.                             -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(": '''..:'!`\\ '-          -                   `");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("-   ,HMb.H|      .    _   -                 .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" : ,MMMMMMMb.    ..                         .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  .`HMMMMMMMM?                             .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  `.`9M#*HMMMM                            :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    -.'   '##*      `b,                  .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("      .      `     ,/'                 .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("       ` .                          ..'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("           - .                  ..-");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("              '`*#d##c.._\\v----`");
    }

    static void g16f() {
        int x = 18;
        int y = 13;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().setPosicaoCursor(y, x);
        Fjalp2.getTerminal().escreva("              _,o#bH\\??::?o?cbo_");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          .o#MH#**SH''' '`*H#'*#MHo_");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("        oHMMMH^  ^'    -  `      '*HHo.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("     .dMMM#'>>-                     `HM?.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    ,MH:R_o/                         `*MH\\");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   dMM' '                               'ML");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  HMR! '                                 `#k");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" d&'.                          -.          `L");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":M ::     `                                 `-");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("/| !|                                        -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("k.$-'                                        :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("}9R:!,,_.                                    .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("\\::\\':`*M#\\-'.                             -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(": '''..:'!`\\ '-          -                   `");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("-   ,HMb.H|      .    _   -                 .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" : ,MMMMMMMb.    ..                         .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().setCorFonte(CorFonte.CYAN);
        Fjalp2.getTerminal().escreva("  .`HMMMMMMMM?                             .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  `.`9M#*HMMMM                            :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    -.'   '##*      `b,                  .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("      .      `     ,/'                 .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("       ` .                          ..'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("           - .                  ..-");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("              '`*#d##c.._\\v----`");
    }

    static void g18() {
        int x = 18;
        int y = 13;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().setPosicaoCursor(y, x);
        Fjalp2.getTerminal().escreva("              _oo#H&d#b?\\b:_>>\\_");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          .oHMMMMMMH*'*9R''-``*#P\\-_");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("        oHMMMMMMMMM$  .'       '   `^-");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("     .dMMMMMMMMH*',?-                 '\\.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    ,MMMMMMM:?}.,d'                     `.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   dMMMMMMMH  /''                         :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  HMMMMMMM&' -                             -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" dPTMMP>' :                           -.    :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().setCorFonte(CorFonte.CYAN);
        Fjalp2.getTerminal().escreva("|? -MM}  .\\                                  .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("J' ::*'  -$L                                 .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":  ?b .,H- '                                 :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("-  |6.&MP:: !.,_.                            -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":   `\\:: '' '`:'MM#,-^,           -          :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("-     ````:' _.:'?``\\  `-                    .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":         .?bMML.]#        -   _  `      .  .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" -      .o#MMMMMMMMH\\    \\.         .       .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  -     `HMMMMMMMMMMMH                     :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  `.     `HMM#*#MMMMMH'                   -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    -.     '    ``##*'      i+           :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("      -            `'     v/'          .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("       `-                           ..'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          ' .                    .-");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("              '`*##HMH##:__,-.-`");
    }

    static void g18f() {
        int x = 18;
        int y = 13;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().setPosicaoCursor(y, x);
        Fjalp2.getTerminal().escreva("              _oo#H&d#b?\\b:_>>\\_");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          .oHMMMMMMH*'*9R''-``*#P\\-_");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("        oHMMMMMMMMM$  .'       '   `^-");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("     .dMMMMMMMMH*',?-                 '\\.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    ,MMMMMMM:?}.,d'                     `.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   dMMMMMMMH  /''                         :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  HMMMMMMM&' -                             -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" dPTMMP>' :                           -.    :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("|? -MM}  .\\                                  .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("J' ::*'  -$L                                 .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":  ?b .,H- '                                 :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("-  |6.&MP:: !.,_.                            -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":   `\\:: '' '`:'MM#,-^,           -          :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("-     ````:' _.:'?``\\  `-                    .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":         .?bMML.]#        -   _  `      .  .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" -      .o#MMMMMMMMH\\    \\.         .       .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().setCorFonte(CorFonte.CYAN);
        Fjalp2.getTerminal().escreva("  -     `HMMMMMMMMMMMH                     :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  `.     `HMM#*#MMMMMH'                   -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    -.     '    ``##*'      i+           :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("      -            `'     v/'          .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("       `-                           ..'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          ' .                    .-");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("              '`*##HMH##:__,-.-`");
    }

    static void g20() {
        int x = 18;
        int y = 13;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().setPosicaoCursor(y, x);
        Fjalp2.getTerminal().escreva("              _,dd#HMb&dHo?\\?:\\_");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          .oHMMMMMMMMMMMH***9P'`'\\v.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("        oHMMMMMMMMMMMMMMM>  `'      -.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("     .dMMMMMMMMMMMMMMMH*'|~-'          .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    ,MMMMMMMMMMMMM6>`H._,&              -.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   dMMMMMMMMMMMMMMM|  `'                  .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  H*MMMMMMMMMMMMMH&. -                     .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" d' HMM''&MMMPT'' :.                      `.-");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().setCorFonte(CorFonte.CYAN);
        Fjalp2.getTerminal().escreva(",'  MP   `TMMM,   |:        .                -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("|   #:    ? *'   : &L                        :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("!   `'   /?H   ,#r `'                        :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(".         ?M: HMM^<~->,o._                   :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":          `9:::'`*-``':`9MHb,|-,         '  :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(".             `'''':' :_ ''!'^.  `|          :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("`.                 _dbHM6_|H.      .   . '  .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" \\             _odHMMMMMMMMH,    ..  `      :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" `-             |MMMMMMMMMMMMM|            :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  `.             9MMH**#MMMMMH'           :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    -.            '     '?##'      d     :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("      .                    '    ,/'    .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("       `..                          ..'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          `  .                   .-");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("              '`'#HHMMMMM#<>..-`");
    }

    static void g20f() {
        int x = 18;
        int y = 13;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().setPosicaoCursor(y, x);
        Fjalp2.getTerminal().escreva("              _,dd#HMb&dHo?\\?:\\_");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          .oHMMMMMMMMMMMH***9P'`'\\v.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("        oHMMMMMMMMMMMMMMM>  `'      -.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("     .dMMMMMMMMMMMMMMMH*'|~-'          .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    ,MMMMMMMMMMMMM6>`H._,&              -.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   dMMMMMMMMMMMMMMM|  `'                  .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  H*MMMMMMMMMMMMMH&. -                     .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" d' HMM''&MMMPT'' :.                      `.-");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(",'  MP   `TMMM,   |:        .                -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("|   #:    ? *'   : &L                        :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("!   `'   /?H   ,#r `'                        :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(".         ?M: HMM^<~->,o._                   :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":          `9:::'`*-``':`9MHb,|-,         '  :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(".             `'''':' :_ ''!'^.  `|          :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("`.                 _dbHM6_|H.      .   . '  .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" \\             _odHMMMMMMMMH,    ..  `      :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().setCorFonte(CorFonte.CYAN);
        Fjalp2.getTerminal().escreva(" `-             |MMMMMMMMMMMMM|            :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  `.             9MMH**#MMMMMH'           :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    -.            '     '?##'      d     :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("      .                    '    ,/'    .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("       `..                          ..'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          `  .                   .-");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("              '`'#HHMMMMM#<>..-`");
    }

    static void g23() {
        int x = 18;
        int y = 13;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().setPosicaoCursor(y, x);
        Fjalp2.getTerminal().escreva("              .,:,#&6dHHHb&##o\\_");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          .oHHMMMMMMMMMMMMMMMMMH*\\,.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("        oHMMMMMMMMMMMMMMMMMMMMMMHb:'-.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("     .dMMMMMMMMMMMMMMMMMMMMMMMMMH|\\/' .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    ,&HMMMMMMMMMMMMMMMMMMMMMMM/'&.,d.   -.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   dboMMHMMMMMMMMMMMMMMMMMMMMMML `'       .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  HMHMMM$Z***MMMMMMMMMMMMMMMMMM|.-         .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" dMM}MMMM#'  `9MMMH?'`MMMMR'T'  _           :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().setCorFonte(CorFonte.CYAN);
        Fjalp2.getTerminal().escreva("|MMMbM#''     |MM'    ``MMMH.   <_           .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("dMMMM#&        *&.     .?`*'   .'&:          .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("MMMMMH-         `'    -v/H   .dD ''  '       :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("MMMM*                  `*M: 4MM*::-!v,_      :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("MMMM                     `*?::' ''``'?9Mb::. :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("&MMM,                       `''''|'._ '?`| - :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("`MMM}.H                          ,#dM[_H   ..:");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" 9MMi`M: .                   .ooHMMMMMMM,  ..");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  9Mb `-                     1MMMMMMMMMM|  :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   ?M                        |MM#*#MMMM*  .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    -.                       `     |#'' ,'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("      .                            -' v`");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("        -.                          .-");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("           - .                   . `");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("              '-*#d#HHMMMMHH#'-'");
    }

    static void g23f() {
        int x = 18;
        int y = 13;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().setPosicaoCursor(y, x);
        Fjalp2.getTerminal().escreva("              .,:,#&6dHHHb&##o\\_");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          .oHHMMMMMMMMMMMMMMMMMH*\\,.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("        oHMMMMMMMMMMMMMMMMMMMMMMHb:'-.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("     .dMMMMMMMMMMMMMMMMMMMMMMMMMH|\\/' .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    ,&HMMMMMMMMMMMMMMMMMMMMMMM/'&.,d.   -.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   dboMMHMMMMMMMMMMMMMMMMMMMMMML `'       .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  HMHMMM$Z***MMMMMMMMMMMMMMMMMM|.-         .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" dMM}MMMM#'  `9MMMH?'`MMMMR'T'  _           :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("|MMMbM#''     |MM'    ``MMMH.   <_           .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("dMMMM#&        *&.     .?`*'   .'&:          .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("MMMMMH-         `'    -v/H   .dD ''  '       :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("MMMM*                  `*M: 4MM*::-!v,_      :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("MMMM                     `*?::' ''``'?9Mb::. :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("&MMM,                       `''''|'._ '?`| - :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("`MMM}.H                          ,#dM[_H   ..:");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" 9MMi`M: .                   .ooHMMMMMMM,  ..");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().setCorFonte(CorFonte.CYAN);
        Fjalp2.getTerminal().escreva("  9Mb `-                     1MMMMMMMMMM|  :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   ?M                        |MM#*#MMMM*  .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    -.                       `     |#'' ,'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("      .                            -' v`");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("        -.                          .-");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("           - .                   . `");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("              '-*#d#HHMMMMHH#'-'");
    }

    static void g25() {
        int x = 18;
        int y = 13;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().setPosicaoCursor(y, x);
        Fjalp2.getTerminal().escreva("              _o,d_?dZdoHHHb#b\\_");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          .vdMMMMMMMMMMMMMMMMMMMMH\\.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("       .,HHMMMMMMMMMMMMMMMMMMMMMMMMH&,.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("      /?RMMMMMMMMMMMMMMMMMMMMMMMMMMMMH|..");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   ,\\?>`T#RMMMMMMMMMMMMMMMMMMMMMMMM6` |/");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   dMMbd#ooHMMMHMMMMMMMMMMMMMMMMMMMMMH,`' '");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  HMMMMMMMTMMMMb$ZP**HMMMMMMMMMMMMMMMM|.   :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" dMMMMMMMM}$MMMMMH'   `HMMMH?'`MMMM?T' .    :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("|MMMMMMMMMMoMH*''      `MM?    ``MMM|  +\\   .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("1MMMMMMMMMMMb#/         ?#?      |`#'  -T:   :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("*'HMMMMMMMMMM*'           '     ~?&  .?} ' ' .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("- 4MMMMMMMMP'                     `M? HMTc:\\.:");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(": `MMMMMMM[                       '#:::`>`'?M{");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(".  |MMMMMMH.                        ``'``'_`:-");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("-  |MMMMMMM|.dD                         ,#Mb\\'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" :  *MMMMM: iM|  .                   _oHMMMM:");
        Fjalp2.getTerminal().setCorFonte(CorFonte.CYAN);
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  .  ?MMMM'  ''                     ,MMMMMMP");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   :  `HMH                          JM#*MMT");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    -.  '                           `   #'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("      .                                /");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("        -.            -              .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("           -.                    . `");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("              '--=&&MH##HMHH#'''");
    }

    static void g25f() {
        int x = 18;
        int y = 13;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().setPosicaoCursor(y, x);
        Fjalp2.getTerminal().escreva("              _o,d_?dZdoHHHb#b\\_");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          .vdMMMMMMMMMMMMMMMMMMMMH\\.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("       .,HHMMMMMMMMMMMMMMMMMMMMMMMMH&,.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("      /?RMMMMMMMMMMMMMMMMMMMMMMMMMMMMH|..");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   ,\\?>`T#RMMMMMMMMMMMMMMMMMMMMMMMM6` |/");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   dMMbd#ooHMMMHMMMMMMMMMMMMMMMMMMMMMH,`' '");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  HMMMMMMMTMMMMb$ZP**HMMMMMMMMMMMMMMMM|.   :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" dMMMMMMMM}$MMMMMH'   `HMMMH?'`MMMM?T' .    :");
        Fjalp2.getTerminal().setCorFonte(CorFonte.CYAN);
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("|MMMMMMMMMMoMH*''      `MM?    ``MMM|  +\\   .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("1MMMMMMMMMMMb#/         ?#?      |`#'  -T:   :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("*'HMMMMMMMMMM*'           '     ~?&  .?} ' ' .");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("- 4MMMMMMMMP'                     `M? HMTc:\\.:");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(": `MMMMMMM[                       '#:::`>`'?M{");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(".  |MMMMMMH.                        ``'``'_`:-");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("-  |MMMMMMM|.dD                         ,#Mb\\'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" :  *MMMMM: iM|  .                   _oHMMMM:");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  .  ?MMMM'  ''                     ,MMMMMMP");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   :  `HMH                          JM#*MMT");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    -.  '                           `   #'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("      .                                /");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("        -.            -              .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("           -.                    . `");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("              '--=&&MH##HMHH#'''");
    }

    static void g29() {
        int x = 18;
        int y = 13;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().setPosicaoCursor(y, x);
        Fjalp2.getTerminal().escreva("              _vo~^'':&b::d,#b\\_");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          ..`' `:v +9P]MMMMMMMMMMHo_");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("        ,-     ?Mb#MMMMMMMMMMMMMMMMMHo.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("     . '     ,ooM*&&&HMMMMMMMMMMMMMMMMHb.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    .   -    99Soo?|'`*?##HMMMMMMMMMMMMMH\\");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   -       .HMMMMMM#od#boodMMMMHMMMMMMMMMMb");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  -      :MMMMMMMMMMMMMMMM67HMMH&$R**HMMMMMb");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" :      .MMMMMMMMMMMMMMMMMMM/HMMMMM|  `9MM'HL");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":       {MMMMMMMMMMMMMMMMMMMM\\MM*''   `H[ `9|");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("|       `HMMMMMMMMMMMMMMMMMMMMb##|      `F. :?");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("H        `'*'''`#MMMMMMMMMMMMMMM?         '  k");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("M.               MMMMMMMMMMMMM''             H'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("MMH.             `HMMMMMMMMMM:               |");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("&MM|              `MMMMMMMMMM,               -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("`MM|              dMMMMMMMMMM|.oH            :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" 9ML              `HMMMMMMM?  dH'           -");
        Fjalp2.getTerminal().setCorFonte(CorFonte.CYAN);
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  Hi               |MMMMMMP   ''           .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   T.               `MMM#'                -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    `.               `                  .`");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("     `                                 -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("       `.. .                        ..'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("           ...                   .-");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("              '-. //######M#b~''");
    }

    static void g29f() {
        int x = 18;
        int y = 13;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().setPosicaoCursor(y, x);
        Fjalp2.getTerminal().escreva("              _vo~^'':&b::d,#b\\_");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("          ..`' `:v +9P]MMMMMMMMMMHo_");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("        ,-     ?Mb#MMMMMMMMMMMMMMMMMHo.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("     . '     ,ooM*&&&HMMMMMMMMMMMMMMMMHb.");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    .   -    99Soo?|'`*?##HMMMMMMMMMMMMMH\\");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   -       .HMMMMMM#od#boodMMMMHMMMMMMMMMMb");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  -      :MMMMMMMMMMMMMMMM67HMMH&$R**HMMMMMb");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" :      .MMMMMMMMMMMMMMMMMMM/HMMMMM|  `9MM'HL");
        Fjalp2.getTerminal().setCorFonte(CorFonte.CYAN);
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(":       {MMMMMMMMMMMMMMMMMMMM\\MM*''   `H[ `9|");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("|       `HMMMMMMMMMMMMMMMMMMMMb##|      `F. :?");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("H        `'*'''`#MMMMMMMMMMMMMMM?         '  k");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("M.               MMMMMMMMMMMMM''             H'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("MMH.             `HMMMMMMMMMM:               |");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("&MM|              `MMMMMMMMMM,               -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("`MM|              dMMMMMMMMMM|.oH            :");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva(" 9ML              `HMMMMMMM?  dH'           -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("  Hi               |MMMMMMP   ''           .'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("   T.               `MMM#'                -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("    `.               `                  .`");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("     `                                 -");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("       `.. .                        ..'");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("           ...                   .-");
        Fjalp2.getTerminal().setPosicaoCursor(y = y + 1, x);
        Fjalp2.getTerminal().escreva("              '-. //######M#b~''");
    }

    static void g42() {
        int x = 18;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().setPosicaoCursor(13, x);
        Fjalp2.getTerminal().escreva("              _oo##'9MMHb':'-,o_");
        Fjalp2.getTerminal().setPosicaoCursor(14, x);
        Fjalp2.getTerminal().escreva("          .oH':HH$' '''  ''-\\7*R&o_");
        Fjalp2.getTerminal().setPosicaoCursor(15, x);
        Fjalp2.getTerminal().escreva("       .oHMMMHMH#9:         '\\bMMMMHo.");
        Fjalp2.getTerminal().setPosicaoCursor(16, x);
        Fjalp2.getTerminal().escreva("      dMMMMMM*'''`'           .oHM'H9MM?.");
        Fjalp2.getTerminal().setPosicaoCursor(17, x);
        Fjalp2.getTerminal().escreva("    ,MMMMMM'                   'HLbd<|?&H\\");
        Fjalp2.getTerminal().setPosicaoCursor(18, x);
        Fjalp2.getTerminal().escreva("   JMMH#H'                     |MMMMM#b>bHb");
        Fjalp2.getTerminal().setPosicaoCursor(19, x);
        Fjalp2.getTerminal().escreva("  :MH  .'\\                  `|MMMMMMMMMMMM&");
        Fjalp2.getTerminal().setPosicaoCursor(20, x);
        Fjalp2.getTerminal().escreva(" .:M:d-'|:b..                 9MMMMMMMMMMMMM+");
        Fjalp2.getTerminal().setPosicaoCursor(21, x);
        Fjalp2.getTerminal().escreva(":  '*H|      -                &MMMMMMMMMMMMMH:");
        Fjalp2.getTerminal().setPosicaoCursor(22, x);
        Fjalp2.getTerminal().escreva(".    `LvdHH#d?                `?MMMMMMMMMMMMMb");
        Fjalp2.getTerminal().setPosicaoCursor(23, x);
        Fjalp2.getTerminal().escreva(":      iMMMMMMH#b               `'*'''#HMMMMMM");
        Fjalp2.getTerminal().setPosicaoCursor(24, x);
        Fjalp2.getTerminal().escreva(".   . ,MMMMMMMMMMb\\.                  {MMMMMH");
        Fjalp2.getTerminal().setPosicaoCursor(25, x);
        Fjalp2.getTerminal().escreva("-     |MMMMMMMMMMMMMMHb,               `MMMMM|");
        Fjalp2.getTerminal().setPosicaoCursor(26, x);
        Fjalp2.getTerminal().escreva(":      |MMMMMMMMMMMMMMH'                &MMMM,");
        Fjalp2.getTerminal().setPosicaoCursor(27, x);
        Fjalp2.getTerminal().escreva("-       `#MMMMMMMMMMMM                 |MMMM6-");
        Fjalp2.getTerminal().setPosicaoCursor(28, x);
        Fjalp2.getTerminal().escreva(" :        `MMMMMMMMMM+                 ]MMMT/");
        Fjalp2.getTerminal().setPosicaoCursor(29, x);
        Fjalp2.getTerminal().escreva("  .       `MMMMMMMP'                   HMM*`");
        Fjalp2.getTerminal().setPosicaoCursor(30, x);
        Fjalp2.getTerminal().escreva("   -       |MMMMMH'                   ,M#'-");
        Fjalp2.getTerminal().setPosicaoCursor(31, x);
        Fjalp2.getTerminal().escreva("    '.     :MMMH|                       .-");
        Fjalp2.getTerminal().setPosicaoCursor(32, x);
        Fjalp2.getTerminal().escreva("      .     |MM                        -");
        Fjalp2.getTerminal().setPosicaoCursor(33, x);
        Fjalp2.getTerminal().escreva("       ` .   `#?..    .             ..'");
        Fjalp2.getTerminal().setPosicaoCursor(34, x);
        Fjalp2.getTerminal().escreva("           -.     _.             .-");
        Fjalp2.getTerminal().setCorFonte(CorFonte.CYAN);
        Fjalp2.getTerminal().setPosicaoCursor(35, x);
        Fjalp2.getTerminal().escreva("              '-|.#qo__,,ob=~~-''");

    }

    static void g42f() {
        int x = 18;
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().limparTela();
        Fjalp2.getTerminal().caixa(0, 0, 80, 55);
        Fjalp2.getTerminal().setCorFonte(CorFonte.VERDE);
        Fjalp2.getTerminal().setPosicaoCursor(13, x);
        Fjalp2.getTerminal().escreva("              _oo##'9MMHb':'-,o_");
        Fjalp2.getTerminal().setCorFonte(CorFonte.CYAN);
        Fjalp2.getTerminal().setPosicaoCursor(14, x);
        Fjalp2.getTerminal().escreva("          .oH':HH$' '''  ''-\\7*R&o_");
        Fjalp2.getTerminal().setPosicaoCursor(15, x);
        Fjalp2.getTerminal().escreva("       .oHMMMHMH#9:         '\\bMMMMHo.");
        Fjalp2.getTerminal().setPosicaoCursor(16, x);
        Fjalp2.getTerminal().escreva("      dMMMMMM*'''`'           .oHM'H9MM?.");
        Fjalp2.getTerminal().setPosicaoCursor(17, x);
        Fjalp2.getTerminal().escreva("    ,MMMMMM'                   'HLbd<|?&H\\");
        Fjalp2.getTerminal().setPosicaoCursor(18, x);
        Fjalp2.getTerminal().escreva("   JMMH#H'                     |MMMMM#b>bHb");
        Fjalp2.getTerminal().setPosicaoCursor(19, x);
        Fjalp2.getTerminal().escreva("  :MH  .'\\                  `|MMMMMMMMMMMM&");
        Fjalp2.getTerminal().setPosicaoCursor(20, x);
        Fjalp2.getTerminal().escreva(" .:M:d-'|:b..                 9MMMMMMMMMMMMM+");
        Fjalp2.getTerminal().setPosicaoCursor(21, x);
        Fjalp2.getTerminal().escreva(":  '*H|      -                &MMMMMMMMMMMMMH:");
        Fjalp2.getTerminal().setPosicaoCursor(22, x);
        Fjalp2.getTerminal().escreva(".    `LvdHH#d?                `?MMMMMMMMMMMMMb");
        Fjalp2.getTerminal().setPosicaoCursor(23, x);
        Fjalp2.getTerminal().escreva(":      iMMMMMMH#b               `'*'''#HMMMMMM");
        Fjalp2.getTerminal().setPosicaoCursor(24, x);
        Fjalp2.getTerminal().escreva(".   . ,MMMMMMMMMMb\\.                  {MMMMMH");
        Fjalp2.getTerminal().setPosicaoCursor(25, x);
        Fjalp2.getTerminal().escreva("-     |MMMMMMMMMMMMMMHb,               `MMMMM|");
        Fjalp2.getTerminal().setPosicaoCursor(26, x);
        Fjalp2.getTerminal().escreva(":      |MMMMMMMMMMMMMMH'                &MMMM,");
        Fjalp2.getTerminal().setPosicaoCursor(27, x);
        Fjalp2.getTerminal().escreva("-       `#MMMMMMMMMMMM                 |MMMM6-");
        Fjalp2.getTerminal().setPosicaoCursor(28, x);
        Fjalp2.getTerminal().escreva(" :        `MMMMMMMMMM+                 ]MMMT/");
        Fjalp2.getTerminal().setPosicaoCursor(29, x);
        Fjalp2.getTerminal().escreva("  .       `MMMMMMMP'                   HMM*`");
        Fjalp2.getTerminal().setPosicaoCursor(30, x);
        Fjalp2.getTerminal().escreva("   -       |MMMMMH'                   ,M#'-");
        Fjalp2.getTerminal().setPosicaoCursor(31, x);
        Fjalp2.getTerminal().escreva("    '.     :MMMH|                       .-");
        Fjalp2.getTerminal().setPosicaoCursor(32, x);
        Fjalp2.getTerminal().escreva("      .     |MM                        -");
        Fjalp2.getTerminal().setPosicaoCursor(33, x);
        Fjalp2.getTerminal().escreva("       ` .   `#?..    .             ..'");
        Fjalp2.getTerminal().setPosicaoCursor(34, x);
        Fjalp2.getTerminal().escreva("           -.     _.             .-");
        Fjalp2.getTerminal().setPosicaoCursor(35, x);
        Fjalp2.getTerminal().escreva("              '-|.#qo__,,ob=~~-''");

    }

    public static void animacao() {
        g4();
        Sound.playSound("terragirando2.wav");
        l1();
        aguardar(1);
        g6();
        l2();
        aguardar(1);
        g8();
        l3();
        aguardar(1);
        g10();
        l1();
        aguardar(1);
        // primeira mudança de cor
        g16();
        l2();
        aguardar(1);
        g18();
        l3();
        aguardar(1);
        g20();
        l1();
        aguardar(1);
        g23();
        l2();
        aguardar(1);
        // segunda mudança de cor
        g25();
        l3();
        aguardar(1);
        g29();
        l1();
        aguardar(1);
        g2();
        l2();
        aguardar(1);
        g42();
        l3();
        aguardar(1);
        aguardar(1);
        Sound.playSound("bemvindo.wav");
    }

    public static void animacaofinal() {
        g4f();
        Sound.playSound("terragirando2.wav");
        f1();
        aguardar(1);
        g6f();
        f2();
        aguardar(1);
        g8f();
        f3();
        aguardar(1);
        g10f();
        f1();
        aguardar(1);
        // primeira mudança de cor
        g16f();
        f2();
        aguardar(1);
        g18f();
        f3();
        aguardar(1);
        g20f();
        f1();
        aguardar(1);
        g23f();
        f2();
        aguardar(1);
        // segunda mudança de cor
        g25f();
        f3();
        aguardar(1);
        g29f();
        f1();
        aguardar(1);
        g2f();
        f2();
        aguardar(1);
        g42f();
        f3();
        aguardar(1);
        g4();
        f1();
        Sound.playSound("atelogo.wav");
        aguardar(1);
        aguardar(1);
        aguardar(1);
    }
}
